server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql:///springboot?serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: '000823'

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # 自动生成表
    database-platform: org.hibernate.dialect.MySQL57Dialect